// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// BlogQueryClient is the client API for BlogQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlogQueryClient interface {
	QueryAllBlog(ctx context.Context, in *QueryAllBlogRequest, opts ...grpc.CallOption) (*QueryAllBlogReply, error)
}

type blogQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogQueryClient(cc grpc.ClientConnInterface) BlogQueryClient {
	return &blogQueryClient{cc}
}

var blogQueryQueryAllBlogStreamDesc = &grpc.StreamDesc{
	StreamName: "QueryAllBlog",
}

func (c *blogQueryClient) QueryAllBlog(ctx context.Context, in *QueryAllBlogRequest, opts ...grpc.CallOption) (*QueryAllBlogReply, error) {
	out := new(QueryAllBlogReply)
	err := c.cc.Invoke(ctx, "/service.BlogQuery/QueryAllBlog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogQueryService is the service API for BlogQuery service.
// Fields should be assigned to their respective handler implementations only before
// RegisterBlogQueryService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type BlogQueryService struct {
	QueryAllBlog func(context.Context, *QueryAllBlogRequest) (*QueryAllBlogReply, error)
}

func (s *BlogQueryService) queryAllBlog(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllBlogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.QueryAllBlog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/service.BlogQuery/QueryAllBlog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.QueryAllBlog(ctx, req.(*QueryAllBlogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterBlogQueryService registers a service implementation with a gRPC server.
func RegisterBlogQueryService(s grpc.ServiceRegistrar, srv *BlogQueryService) {
	srvCopy := *srv
	if srvCopy.QueryAllBlog == nil {
		srvCopy.QueryAllBlog = func(context.Context, *QueryAllBlogRequest) (*QueryAllBlogReply, error) {
			return nil, status.Errorf(codes.Unimplemented, "method QueryAllBlog not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "service.BlogQuery",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "QueryAllBlog",
				Handler:    srvCopy.queryAllBlog,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "blog_service.proto",
	}

	s.RegisterService(&sd, nil)
}

// NewBlogQueryService creates a new BlogQueryService containing the
// implemented methods of the BlogQuery service in s.  Any unimplemented
// methods will result in the gRPC server returning an UNIMPLEMENTED status to the client.
// This includes situations where the method handler is misspelled or has the wrong
// signature.  For this reason, this function should be used with great care and
// is not recommended to be used by most users.
func NewBlogQueryService(s interface{}) *BlogQueryService {
	ns := &BlogQueryService{}
	if h, ok := s.(interface {
		QueryAllBlog(context.Context, *QueryAllBlogRequest) (*QueryAllBlogReply, error)
	}); ok {
		ns.QueryAllBlog = h.QueryAllBlog
	}
	return ns
}

// UnstableBlogQueryService is the service API for BlogQuery service.
// New methods may be added to this interface if they are added to the service
// definition, which is not a backward-compatible change.  For this reason,
// use of this type is not recommended.
type UnstableBlogQueryService interface {
	QueryAllBlog(context.Context, *QueryAllBlogRequest) (*QueryAllBlogReply, error)
}
