// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: phase_service.proto

package service

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	model "makeaplan.com/api/model"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type QueryPhaseSummaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhaseId int32 `protobuf:"varint,1,opt,name=phase_id,json=phaseId,proto3" json:"phase_id,omitempty"`
	PlanId  int32 `protobuf:"varint,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
}

func (x *QueryPhaseSummaryRequest) Reset() {
	*x = QueryPhaseSummaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phase_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryPhaseSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPhaseSummaryRequest) ProtoMessage() {}

func (x *QueryPhaseSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phase_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPhaseSummaryRequest.ProtoReflect.Descriptor instead.
func (*QueryPhaseSummaryRequest) Descriptor() ([]byte, []int) {
	return file_phase_service_proto_rawDescGZIP(), []int{0}
}

func (x *QueryPhaseSummaryRequest) GetPhaseId() int32 {
	if x != nil {
		return x.PhaseId
	}
	return 0
}

func (x *QueryPhaseSummaryRequest) GetPlanId() int32 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

type QueryPhaseSummaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phase *model.PhaseSummary `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
}

func (x *QueryPhaseSummaryResponse) Reset() {
	*x = QueryPhaseSummaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phase_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryPhaseSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPhaseSummaryResponse) ProtoMessage() {}

func (x *QueryPhaseSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_phase_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPhaseSummaryResponse.ProtoReflect.Descriptor instead.
func (*QueryPhaseSummaryResponse) Descriptor() ([]byte, []int) {
	return file_phase_service_proto_rawDescGZIP(), []int{1}
}

func (x *QueryPhaseSummaryResponse) GetPhase() *model.PhaseSummary {
	if x != nil {
		return x.Phase
	}
	return nil
}

type QueryPlanPhaseSummaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlanId int32 `protobuf:"varint,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
}

func (x *QueryPlanPhaseSummaryRequest) Reset() {
	*x = QueryPlanPhaseSummaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phase_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryPlanPhaseSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPlanPhaseSummaryRequest) ProtoMessage() {}

func (x *QueryPlanPhaseSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phase_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPlanPhaseSummaryRequest.ProtoReflect.Descriptor instead.
func (*QueryPlanPhaseSummaryRequest) Descriptor() ([]byte, []int) {
	return file_phase_service_proto_rawDescGZIP(), []int{2}
}

func (x *QueryPlanPhaseSummaryRequest) GetPlanId() int32 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

type QueryPlanPhaseSummaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phases []*model.PhaseSummary `protobuf:"bytes,1,rep,name=phases,proto3" json:"phases,omitempty"`
}

func (x *QueryPlanPhaseSummaryResponse) Reset() {
	*x = QueryPlanPhaseSummaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phase_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryPlanPhaseSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPlanPhaseSummaryResponse) ProtoMessage() {}

func (x *QueryPlanPhaseSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_phase_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPlanPhaseSummaryResponse.ProtoReflect.Descriptor instead.
func (*QueryPlanPhaseSummaryResponse) Descriptor() ([]byte, []int) {
	return file_phase_service_proto_rawDescGZIP(), []int{3}
}

func (x *QueryPlanPhaseSummaryResponse) GetPhases() []*model.PhaseSummary {
	if x != nil {
		return x.Phases
	}
	return nil
}

type UpdatePhaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhaseId   int32                 `protobuf:"varint,1,opt,name=phase_id,json=phaseId,proto3" json:"phase_id,omitempty"`
	Title     string                `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Note      *wrappers.StringValue `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	StartTime *timestamp.Timestamp  `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   *timestamp.Timestamp  `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *UpdatePhaseRequest) Reset() {
	*x = UpdatePhaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phase_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePhaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePhaseRequest) ProtoMessage() {}

func (x *UpdatePhaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phase_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePhaseRequest.ProtoReflect.Descriptor instead.
func (*UpdatePhaseRequest) Descriptor() ([]byte, []int) {
	return file_phase_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePhaseRequest) GetPhaseId() int32 {
	if x != nil {
		return x.PhaseId
	}
	return 0
}

func (x *UpdatePhaseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdatePhaseRequest) GetNote() *wrappers.StringValue {
	if x != nil {
		return x.Note
	}
	return nil
}

func (x *UpdatePhaseRequest) GetStartTime() *timestamp.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *UpdatePhaseRequest) GetEndTime() *timestamp.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type UpdatePhaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePhaseResponse) Reset() {
	*x = UpdatePhaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phase_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePhaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePhaseResponse) ProtoMessage() {}

func (x *UpdatePhaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_phase_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePhaseResponse.ProtoReflect.Descriptor instead.
func (*UpdatePhaseResponse) Descriptor() ([]byte, []int) {
	return file_phase_service_proto_rawDescGZIP(), []int{5}
}

type DeletePhaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhaseId int32 `protobuf:"varint,1,opt,name=phase_id,json=phaseId,proto3" json:"phase_id,omitempty"`
}

func (x *DeletePhaseRequest) Reset() {
	*x = DeletePhaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phase_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePhaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePhaseRequest) ProtoMessage() {}

func (x *DeletePhaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phase_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePhaseRequest.ProtoReflect.Descriptor instead.
func (*DeletePhaseRequest) Descriptor() ([]byte, []int) {
	return file_phase_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePhaseRequest) GetPhaseId() int32 {
	if x != nil {
		return x.PhaseId
	}
	return 0
}

type DeletePhaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePhaseResponse) Reset() {
	*x = DeletePhaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phase_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePhaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePhaseResponse) ProtoMessage() {}

func (x *DeletePhaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_phase_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePhaseResponse.ProtoReflect.Descriptor instead.
func (*DeletePhaseResponse) Descriptor() ([]byte, []int) {
	return file_phase_service_proto_rawDescGZIP(), []int{7}
}

type CreatePhaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlanId    int32                 `protobuf:"varint,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Title     string                `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Note      *wrappers.StringValue `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	StartTime *timestamp.Timestamp  `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime   *timestamp.Timestamp  `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *CreatePhaseRequest) Reset() {
	*x = CreatePhaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phase_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePhaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePhaseRequest) ProtoMessage() {}

func (x *CreatePhaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phase_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePhaseRequest.ProtoReflect.Descriptor instead.
func (*CreatePhaseRequest) Descriptor() ([]byte, []int) {
	return file_phase_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreatePhaseRequest) GetPlanId() int32 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

func (x *CreatePhaseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePhaseRequest) GetNote() *wrappers.StringValue {
	if x != nil {
		return x.Note
	}
	return nil
}

func (x *CreatePhaseRequest) GetStartTime() *timestamp.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *CreatePhaseRequest) GetEndTime() *timestamp.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type CreatePhaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhaseId int32 `protobuf:"varint,1,opt,name=phase_id,json=phaseId,proto3" json:"phase_id,omitempty"`
}

func (x *CreatePhaseResponse) Reset() {
	*x = CreatePhaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_phase_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePhaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePhaseResponse) ProtoMessage() {}

func (x *CreatePhaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_phase_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePhaseResponse.ProtoReflect.Descriptor instead.
func (*CreatePhaseResponse) Descriptor() ([]byte, []int) {
	return file_phase_service_proto_rawDescGZIP(), []int{9}
}

func (x *CreatePhaseResponse) GetPhaseId() int32 {
	if x != nil {
		return x.PhaseId
	}
	return 0
}

var File_phase_service_proto protoreflect.FileDescriptor

var file_phase_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x68, 0x61, 0x73, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x0b,
	0x70, 0x68, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72,
	0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4e, 0x0a, 0x18,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x68, 0x61, 0x73, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x68, 0x61, 0x73,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x68, 0x61, 0x73,
	0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x19,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x68, 0x61, 0x73, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x70, 0x68, 0x61,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x50, 0x68, 0x61, 0x73, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52,
	0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x22, 0x37, 0x0a, 0x1c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50,
	0x6c, 0x61, 0x6e, 0x50, 0x68, 0x61, 0x73, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x22,
	0x4e, 0x0a, 0x1d, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x50, 0x68, 0x61, 0x73,
	0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2d, 0x0a, 0x06, 0x70, 0x68, 0x61, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x68, 0x61, 0x73, 0x65,
	0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x06, 0x70, 0x68, 0x61, 0x73, 0x65, 0x73, 0x22,
	0xe9, 0x01, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x68, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x68, 0x61, 0x73, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x68, 0x61, 0x73, 0x65, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x15, 0x0a, 0x13, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x2f, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x68, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x68, 0x61, 0x73,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x68, 0x61, 0x73,
	0x65, 0x49, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x68, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xe7, 0x01, 0x0a, 0x12, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x30, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x04, 0x6e, 0x6f,
	0x74, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x35, 0x0a,
	0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x65, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0x30, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x68,
	0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70,
	0x68, 0x61, 0x73, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70,
	0x68, 0x61, 0x73, 0x65, 0x49, 0x64, 0x32, 0xd4, 0x01, 0x0a, 0x0a, 0x50, 0x68, 0x61, 0x73, 0x65,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x68, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x6c,
	0x61, 0x6e, 0x50, 0x68, 0x61, 0x73, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x25,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x6c,
	0x61, 0x6e, 0x50, 0x68, 0x61, 0x73, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x6c, 0x61, 0x6e, 0x50, 0x68, 0x61, 0x73, 0x65, 0x53, 0x75,
	0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x5c, 0x0a, 0x11, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x68, 0x61, 0x73, 0x65, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x12, 0x21, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x50, 0x68, 0x61, 0x73, 0x65, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x68, 0x61, 0x73, 0x65, 0x53, 0x75, 0x6d, 0x6d,
	0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0xf1, 0x01,
	0x0a, 0x0b, 0x50, 0x68, 0x61, 0x73, 0x65, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x12, 0x4a, 0x0a,
	0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x68, 0x61, 0x73, 0x65, 0x12, 0x1b, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x68, 0x61,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x68, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0b, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x50, 0x68, 0x61, 0x73, 0x65, 0x12, 0x1b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x68, 0x61, 0x73, 0x65, 0x12, 0x1b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x1b, 0x5a, 0x19, 0x6d, 0x61, 0x6b, 0x65, 0x61, 0x70, 0x6c, 0x61, 0x6e, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_phase_service_proto_rawDescOnce sync.Once
	file_phase_service_proto_rawDescData = file_phase_service_proto_rawDesc
)

func file_phase_service_proto_rawDescGZIP() []byte {
	file_phase_service_proto_rawDescOnce.Do(func() {
		file_phase_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_phase_service_proto_rawDescData)
	})
	return file_phase_service_proto_rawDescData
}

var file_phase_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_phase_service_proto_goTypes = []interface{}{
	(*QueryPhaseSummaryRequest)(nil),      // 0: service.QueryPhaseSummaryRequest
	(*QueryPhaseSummaryResponse)(nil),     // 1: service.QueryPhaseSummaryResponse
	(*QueryPlanPhaseSummaryRequest)(nil),  // 2: service.QueryPlanPhaseSummaryRequest
	(*QueryPlanPhaseSummaryResponse)(nil), // 3: service.QueryPlanPhaseSummaryResponse
	(*UpdatePhaseRequest)(nil),            // 4: service.UpdatePhaseRequest
	(*UpdatePhaseResponse)(nil),           // 5: service.UpdatePhaseResponse
	(*DeletePhaseRequest)(nil),            // 6: service.DeletePhaseRequest
	(*DeletePhaseResponse)(nil),           // 7: service.DeletePhaseResponse
	(*CreatePhaseRequest)(nil),            // 8: service.CreatePhaseRequest
	(*CreatePhaseResponse)(nil),           // 9: service.CreatePhaseResponse
	(*model.PhaseSummary)(nil),            // 10: service.PhaseSummary
	(*wrappers.StringValue)(nil),          // 11: google.protobuf.StringValue
	(*timestamp.Timestamp)(nil),           // 12: google.protobuf.Timestamp
}
var file_phase_service_proto_depIdxs = []int32{
	10, // 0: service.QueryPhaseSummaryResponse.phase:type_name -> service.PhaseSummary
	10, // 1: service.QueryPlanPhaseSummaryResponse.phases:type_name -> service.PhaseSummary
	11, // 2: service.UpdatePhaseRequest.note:type_name -> google.protobuf.StringValue
	12, // 3: service.UpdatePhaseRequest.start_time:type_name -> google.protobuf.Timestamp
	12, // 4: service.UpdatePhaseRequest.end_time:type_name -> google.protobuf.Timestamp
	11, // 5: service.CreatePhaseRequest.note:type_name -> google.protobuf.StringValue
	12, // 6: service.CreatePhaseRequest.start_time:type_name -> google.protobuf.Timestamp
	12, // 7: service.CreatePhaseRequest.end_time:type_name -> google.protobuf.Timestamp
	2,  // 8: service.PhaseQuery.QueryPlanPhaseSummary:input_type -> service.QueryPlanPhaseSummaryRequest
	0,  // 9: service.PhaseQuery.QueryPhaseSummary:input_type -> service.QueryPhaseSummaryRequest
	8,  // 10: service.PhaseModify.CreatePhase:input_type -> service.CreatePhaseRequest
	6,  // 11: service.PhaseModify.DeletePhase:input_type -> service.DeletePhaseRequest
	4,  // 12: service.PhaseModify.UpdatePhase:input_type -> service.UpdatePhaseRequest
	3,  // 13: service.PhaseQuery.QueryPlanPhaseSummary:output_type -> service.QueryPlanPhaseSummaryResponse
	1,  // 14: service.PhaseQuery.QueryPhaseSummary:output_type -> service.QueryPhaseSummaryResponse
	9,  // 15: service.PhaseModify.CreatePhase:output_type -> service.CreatePhaseResponse
	7,  // 16: service.PhaseModify.DeletePhase:output_type -> service.DeletePhaseResponse
	5,  // 17: service.PhaseModify.UpdatePhase:output_type -> service.UpdatePhaseResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_phase_service_proto_init() }
func file_phase_service_proto_init() {
	if File_phase_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_phase_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryPhaseSummaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phase_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryPhaseSummaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phase_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryPlanPhaseSummaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phase_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryPlanPhaseSummaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phase_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePhaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phase_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePhaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phase_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePhaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phase_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePhaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phase_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePhaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_phase_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePhaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_phase_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_phase_service_proto_goTypes,
		DependencyIndexes: file_phase_service_proto_depIdxs,
		MessageInfos:      file_phase_service_proto_msgTypes,
	}.Build()
	File_phase_service_proto = out.File
	file_phase_service_proto_rawDesc = nil
	file_phase_service_proto_goTypes = nil
	file_phase_service_proto_depIdxs = nil
}
